<?php

declare(strict_types=1);

use Infrangible\CatalogProductOptionWrapper\Block\Product\View\Options\Option;
use Magento\Framework\View\TemplateEngine\Php;

/**
 * @author      Andreas Knollmann
 * @copyright   2014-2025 Softwareentwicklung Andreas Knollmann
 * @license     http://www.opensource.org/licenses/mit-license.php MIT
 */

/** @var Php $this */
/** @var Option $block */

$option = $block->getOption();
?>

<div id="product-option-<?= $option->getId(); ?>" data-option-id="<?= $option->getId(); ?>" class="field-wrapper">
    <?= $block->getOptionHtml(); ?>
</div>
